---
- name: variable usage
  hosts: targets
  gather_facts: no
  become: yes
  become_user: root
  ignore_errors: true
  vars_files:
    - vars.yml
  
  tasks: 
   - name: install 
     apt:
      name: "{{ package }}"
      state: present
 
   - name: service
     service:
      name: "{{ service }}"
      state: started

 


